[package]
name    = "integration_tests"
version.workspace = true
edition.workspace = true
license.workspace = true

[[test]]
name = "test_tensor"
path = "tests/test_tensor.rs"

[[test]]
name = "test_layer"
path = "tests/test_layer.rs"

[[test]]
name = "test_loader"
path = "tests/test_loader.rs"

[[test]]
name = "test_slm"
path = "tests/test_slm.rs"

[[test]]
name = "test_train"
path = "tests/test_train.rs"

[[test]]
name = "test_csv"
path = "tests/test_csv.rs"

[[test]]
name = "test_regression"
path = "tests/test_regression.rs"

[[test]]
name = "test_qat_cache"
path = "tests/test_qat_cache.rs"

[[test]]
name = "integration"
path = "tests/integration.rs"

[[test]]
name = "test_gguf_llm"
path = "tests/test_gguf_llm.rs"

[dependencies]
ferrum_core = { path = "../ferrum_core" }
